config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'
  get "/friendships/:friend_id/new", to: "friendships#create"
  get "/users/logout", to: "sessions#destroy", as: "logout"
  get "/activity_instances/new/:activity_id", to: "activity_instances#create"
  patch "users/:id/happiness", to: "days#update"
  resources :session
  resources :friendships
  resources :activities
  resources :users
  resources :activity_instances

  get "/users/:id/days/:day_id", to: "days#show", as:"day"
  delete "/activity_instance/:activity_id/:day_id", to: "activity_instances#destroy"
  get "/users/:id/days", to: "users#user_history", as: "days"
  post "/users/:id/days", to: "users#user_history_create"
  get "/", to: "sessions#new", as: "login"
  post "/",   to: 'sessions#create'

end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :activity_instances
  has_many :days, through: :activity_instances
  has_many :users, through: :activity_instances
end

app/models/activity_instance.rb
class ActivityInstance < ApplicationRecord
  belongs_to :day
  belongs_to :activity
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def is_today
    self.days.find_by(date: Date.today) ? true:false
  end

  def today
    self.days.find_by(date: Date.today)
  end

end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  has_many :activity_instances
  has_many :activities, through: :activity_instances
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: :User
end

app/models/user.rb
class User < ApplicationRecord
  has_many :days
  has_many :friendships, class_name: "Friendship", foreign_key: "user_id"
  has_many :friends, through: :friendships
  has_many :activity_instances, through: :days
  has_many :activities, through: :activity_instances

  has_secure_password

  validates_uniqueness_of :email
  validates :email, presence: true
  validates :name, presence: true
  validates :password, presence: true
  validates :age, presence: true
  validates :about, presence: true

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :this_activity, only: [:show, :edit, :update, :destroy]

  def index
    @activities = Activity.all
  end

  def show

  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.create(activity_params)
    redirect_to activities_path
  end

  def edit

  end

  def update
    @activity.update(activity_params)
    redirect_to @activity
  end

  def destroy
    all_instances = @activity.activity_instances
    all_instances.each do |instance|
      instance.destroy
    end
    @activity.destroy
    flash[:message] = "#{@activity.name} has been deleted"
    redirect_to activities_path
  end

  private

  def this_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params()
    params.require(:activity).permit(:name, :description, :length, :img_url)
  end
end

app/controllers/activity_instances_controller.rb
class ActivityInstancesController < ApplicationController

  def index
    @days = Day.all
  end

  def create
    check_day
    added_activity = ActivityInstance.create(day_id: @today.id, activity_id: params[:activity_id])
    if added_activity.valid?
      flash[:message] = "Activity Added"
    end
    session[:selected_date] = nil
    redirect_to activities_path
  end

  def check_day
    if session[:selected_date]
      if selected_day = current_user.days.find_by(date: session[:selected_date])
        @today = selected_day
      else
        @today = Day.create(date: session[:selected_date], user_id: current_user.id)
      end
    elsif this_day = current_user.days.find_by(date: Date.today)
      @today = this_day
    else
      @today = Day.create(date: Date.today, user_id: current_user.id)
    end
  end

  def destroy
    @activity_instance = ActivityInstance.find_by(day_id: params[:day_id].to_i, activity_id: params[:activity_id].to_i)
    @activity_instance.destroy
    redirect_to "/users/#{current_user.id}/days/#{params[:day_id]}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user

    def current_user
      # User.find would throw an error if we cannot find the user
      User.find_by({id: session[:user_id]})
    end

    def logged_in?
      !!current_user
    end

    def authorized
      redirect_to '/' unless logged_in?
    end

    def logged_in
      if logged_in?
        redirect_to user_path(current_user)
      end
    end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :this_day, only: [:show, :edit]

  def index
    @days = Day.all
    @users = User.all
  end

  def show
    @day = Day.find(params[:day_id])
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.create(day_params)
    redirect_to day_path(@day)
  end

  def edit

  end

  def update
    @today = current_user.today
    @today.update(happiness: params[:day][:happiness].to_i)
    redirect_to user_path(current_user)
  end

  def destroy

  end

  private

  def this_day
    @day = Day.find(params[:day_id])
  end

  def day_params()
    params.require(:day).permit(:date, :user_id)
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def new
    @users = User.all
    @friendship = Friendship.new
  end

  def create
    @friendship = Friendship.create(user_id: current_user.id, friend_id: params[:friend_id])
    redirect_to user_path(current_user)
  end

end

app/controllers/sessions_controller.rb
  class SessionsController < ApplicationController
    # before_action :authorized comes from ApplicationController
    skip_before_action :authorized, only: [:new, :create, :index]
    before_action :logged_in, only: [:index]

    def new
      render :new
    end

    def create #handles the POST request to /login
      # find out if we have a user with this username
      @user = User.find_by(email: params[:email])
      # get that user record from DB
      # authenticate this user; determine if they provided the correct pw
      if @user && @user.authenticate(params[:password])

        # once we have found the user, create a new session for them
        session[:user_id] = @user.id
        # redirect_to user_path(@user)
        redirect_to @user
      else
        flash[:notice] = 'Enter a valid email and password'
        redirect_to '/'
      end
    end


    def destroy
      session[:user_id] = nil
      redirect_to login_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :this_user, only: [:show, :edit, :update, :destroy, :user_history]

  def index
    @users = User.all
  end

  def show
    @today = current_user.today
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    # byebug
   if @user.valid?
     session[:user_id] = @user.id
    redirect_to @user
  else flash[:notice] = "You need to enter all info!"
    redirect_to new_user_path
    end
  end


  def edit

  end

  def update_day

  end

  def update
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'You deleted ur account.'
    redirect_to '/'
  end

  def user_history
    @day = params[:calendar]
    @calendar = Day.new
    render :user_history
  end

  def user_history_create
    session[:selected_date] = params[:day][:date]
    redirect_to activities_path
  end

  def happiness_show
    if current_user.today[:happiness] != 0
      "Happiness for today: #{current_user.today[:happiness]}"
    else
      "Input Happiness for today: "
    end
  end
  private

  def this_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :name, :age, :about)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_instances_helper.rb
module ActivityInstancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.erb
<%= form_for @activity do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.label :length, "Estimated Time(mins): " %>
  <%= f.number_field :length %><br>
  <%= f.label :img_url, "Picture URL: "%>
  <%= f.text_field :img_url %><br><br>
  <%= f.submit %>
<% end %>

app/views/activities/edit.erb
<div class="container text-center">
  <h1><strong>Edit Activity</strong></h1>
</div>


<div class="af-card-container">
  <div class="activity-edit">
    <div class="new-input-box">
      <%= render "form" %>
      <br>
      <%= button_to "Delete", @activity, :method => :delete %>
      <br>
      <%= button_to "Cancel", activity_path, {method: :get} %>
    </div>
  </div>
</div>

app/views/activities/index.erb
<div class="container text-center">
  <h1><strong>All Activities</strong></h1>
  <% if flash[:message] %>
  <%= flash[:message] %><br>
  <% end %>
  <% if session[:selected_date] %>
    <h4><%= "Add an Activity for #{session[:selected_date]}" %></h4>
  <% else %>
    <h4><%= "Add an Activity for Today" %></h4>
  <% end %>


  <div class="special-card-container">
    <% @activities.each do |activity| %>
      <div class="special-card">
        <div class="special-card-body">
          <img class="center-cropped" src= <%= activity.img_url %> alt="Card image cap">
          <h5 class="card-title"><%= activity.name %></h5>
          <p><%= link_to "Add Activity", "/activity_instances/new/#{activity.id}", method: :get %>
          <%= link_to "More Info", activity_path(activity), {method: :get} %></p>
        </div>
      </div>
    <% end %>
  </div>
  <%= button_to "Create a New Activity", new_activity_path, {method: :get} %>
  <%= button_to "Back", user_path(current_user), {method: :get} %>
</div>

app/views/activities/new.erb
<div class="container text-center">
  <h1><strong>Add Activity to Database</strong></h1>
</div>


<div class="af-card-container">
  <div class="activity-new">
    <div class="new-input-box">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/activities/show.erb
<div class="container text-center">
  <h1><strong><%= @activity.name %></strong></h1>
</div>

  <div class="activity-container">
    <div class="activity-show">
      <img class="picture-crop" src= <%= @activity.img_url %> alt="Card image cap">
      <p class="card-title"><%= @activity.description %></p>
      <p><%= button_to "Edit", edit_activity_path, {method: :get} %>
      <%= button_to "Show All", activities_path, {method: :get} %></p>
    </div>
  </div>

app/views/activity_instances/index.erb
<% @days.each do |day| %>
  <%= day %>
<% end %>

app/views/days/_form.erb
<%= form_for @day do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %><br>

  <%= f.label :user_id %>
  <%= f.number_field :user_id %><br>


  <%= f.submit %>

<% end %>

app/views/days/index.erb
<% @user.days.each do |day| %>
  <%= day.date  %><br>
<% end %>

app/views/days/show.erb
<div class="container text-center">
  <h1><strong><%= @day.date %></strong></h1>
</div>

<div class="af-card-container">
  <div class="date">
    <% @day.activities.each do |activity|%>
      <p><%= activity.name %>
      <%= link_to "<--- delete", "/activity_instance/#{activity.id}/#{params[:day_id]}", :method => :delete, params: {:something => activity.id} %></p>
    <% end %>

    <%= button_to "Back to Activity History", days_path, {method: :get} %>
  </div>
</div>

app/views/friendships/_form.erb
<%= current_user.name %>
<%= form_for @friendship do |f| %>
  <%= f.number_field :friend_id %>
<%= f.submit %>
<% end %>

app/views/friendships/new.erb
<div class="container text-center">
  <h1><strong>Select Friend to Add</strong></h1>
</div>


<div class="af-card-container">
    <div class="friendships">
      <div class="friendship-box">
        <% @users.each do |user| %>
          <% if user.name != current_user.name %>
            <% if !Friendship.find_by(user_id: current_user.id, friend_id: user.id) %>
              <p><%= link_to "#{user.name.capitalize}", "/friendships/#{user.id}/new", method: :get %></p><br>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/homes/index.html.erb
<!DOCTYPE html>
        <header>
            <nav>
                <div class="row">    <!-- <img src="img relative path goes here" alt="Health logo" class="logo"> -->
                </div>
            </nav>
            <div class="main-text-box">
                <h1>Happy Tracker<br>Where happiness starts</h1>
                <%= button_to "Sign Up", new_user_path, {method: :get} %>
                <%= button_to "Log In", '/login', {method: :get} %>

            </div>

        </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HAPPINESS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-expand-lg navbar-dark bg-gray-dark">
      <a class="navbar-brand" href="/">Mindful</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <% if !!current_user %>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto nav-fill w-25">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/activities">Activities</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/users/<%= current_user.id %>/days">History</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="#">Profile</a>
          </li>
        </ul>
        <div class="nav navbar-nav navbar-right">
           <a href= "/users/logout" class="btn btn-secondary my-2 my-sm-0">Logout</a>
        </div>
      </div>
      <% end %>
    </nav>

  </head>

  <body>
<div class="container">
  <%= yield %>

</div>
  </body>
</html>

app/views/users/_form.erb
<%= flash[:notice] %>

<div class="container">
    <%= form_for(@user) do |f| %>
      <%= f.label :email, "Email:" %>
      <%= f.email_field :email, require: true %><br>

      <%= f.label :password, "Password:" %>
      <%= f.password_field :password, require: true %><br>

      <%= f.label :name, "Name:" %>
      <%= f.text_field :name,require: true %><br>

      <%= f.label :age, "Age:" %>
      <%= f.number_field :age, require: true %><br>

      <%= f.label :about, "About:" %><br>
      <%= f.text_area :about, require: true%>
      <br /><br />
      <%= f.submit "Sign Up" %>

    <% end %>
</div>

app/views/users/_happy_form.erb
<%= form_for @today, :url => "#{current_user.id}/happiness" do |f| %>
  <%= f.number_field :happiness %>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<body>

      <div class="box">
          <h2>Sign Up</h2>

        <div class="inputBox">
            <%= render 'form' %>
        </div>
      </div>

  <%= yield %>
</body>

app/views/users/show.html.erb
<div class="container text-center">
  <% if current_user.id == params[:id].to_i %>
    <h1><strong>Welcome back, <%= @user.name.capitalize%></strong></h1>
      <h3>Today's Date: <%= Date.today %></h3>
  <% else %>
    <h1><strong><%= @user.name.capitalize%>'s Profile</strong></h1>
      <h3>Today's Date: <%= Date.today %></h3>
  <% end %>
</div>


<div class="af-card-container">
  <div class="activities">
    <div class="title">
      <h2>Today's Activities:</h2>
    </div>
    <div class="input-box">
      <% if current_user.id == params[:id].to_i %>
        <% if !@user.today %>
          <p><%= "You have no activities for today yet" %></p>
<%# Happiness Update Function Here, still needs work %>
        <%# <% else %>
          <%# <% if @user.today[:happiness] != 0%>
            <!-- <p><%= "Happiness for today:" %></p> -->
            <%# <%= render "happy_form" %>
          <%# <% else %>
            <!-- <p><%= "Happiness for today: No input yet" %></p> -->
            <%# <%= render "happy_form" %>
          <%# <% end %>
<%# Happiness Update form Here %>

        <% end %>
      <% else %>
        <% if !@user.today %>
          <p><%= "User has no activities yet today" %></p>
        <% else %>
          <% if @user.today[:happiness] != 0%>
            <%= "Happiness for today: #{@user.today[:happiness]}" %>
          <% else %>
            <%= "Happiness for today: No input yet" %>
          <% end %>
        <% end %>
      <% end %>
      <div class="activities-list">
        <% if @user.is_today %>
          <% @user.today.activities.each do |activity| %>
            <p>-<%= activity.name %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="bottom-container">
      <%= link_to "View Full Activities History", days_path %>
      <% if current_user.id == params[:id].to_i %>
      <br>
        <%= link_to "View Activities to add", activities_path %>
      <% else %>
        <%= link_to 'Return to your page', user_path(current_user), method: :get %>
      <% end %>
    </div>
  </div>

 <% if current_user.id == params[:id].to_i %>
  <div class="friends">
    <div class="title">
      <h2>Friend's Activity:</h2>
    </div>
    <div class="input-box">
        <% @user.friends.each do |friend| %>
          <p><%= link_to friend.name.capitalize, user_path(friend.id) %></p>
          <% if friend.is_today %>
            <% friend.today.activities.each do |activity| %>
              <ul>
                <p><%= activity.name %></p>
              </ul>
            <% end %>
          <% end %>
        <% end %><br>
    </div>
    <div class="bottom-container">
      <%= link_to "Add Friend", "/friendships/new" %>
  <% end %>
    </div>
  </div>
</div>

app/views/users/showw.html.erb
<%# User's info  %>
<%= @user.name %>
<%= @user.age %>
<%= @user.email %>
<%= @user.password %>
<%= @user.about %>

<br>
<br>
Date:
<%= Date.today %><br>

<% if current_user.id == params[:id].to_i %>
  <% if !@user.today %>
    <%= "You have no activities for today yet" %>
  <% else %>
    <% if  @user.today[:happiness] != 0%>
      <%= "Happiness for today:" %>
      <%= render "happy_form" %>
      Todays Activities:
    <% else %>
      <%= "Happiness for today: No input yet" %>
      <%= render "happy_form" %>
      Todays Activities:
    <% end %>
  <% end %>
<% else %>
  <% if !@user.today %>
    <%= "User has no activities yet today" %>
  <% else %>
    <% if @user.today[:happiness] != 0%>
      <%= "Happiness for today: #{@user.today[:happiness]}" %>
      Todays Activities:
    <% else %>
      <%= "Happiness for today: No input yet" %>
      Todays Activities:
    <% end %>
  <% end %>
<% end %>

<% if @user.is_today %>
  <% @user.today.activities.each do |activity| %>
    <%= activity.name %><br>
  <% end %>
<% end %><br>

<% if current_user.id == params[:id].to_i %>
  <%= link_to "Add activity for today", activities_path %>
<% end %><br>
<%= link_to "View Full Activities History", days_path %>

<br>
<br>
<br>
<% if current_user.id == params[:id].to_i %>
Friends:
  <% @user.friends.each do |friend| %><br>
    <%= link_to friend.name, user_path(friend.id) %><br>
    <% if friend.is_today %>
      <% friend.today.activities.each do |activity| %>
        <%= activity.name %><br>
      <% end %>
    <% end %>
  <% end %><br>
  <%= link_to "Add Friend", "/friendships/new" %>
  <%= button_to 'Logout', '/', method: :delete %>
<% else %>
  <%= button_to 'Return to your page', user_path(current_user), method: :get %>
<% end %>

app/views/users/user_history.erb
<div class="container text-center">
  <h1><strong>Activity History</strong></h1>
</div>


<div class="af-card-container">
  <div class="history">
    <div class="information">
      <% if @user.days != [] %>
        <% @user.days.each do |day| %>
          <h6><%= link_to day.date, "/users/#{current_user.id}/days/#{day.id}"%></h6>
          <% if day.activities == []%>
            <% day.destroy %>
          <% else %>
            <% day.activities.each do |activity|%>
              <p><%= activity.name %></p>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <p><%= "User has no Activity History yet" %></p>
      <% end %>
    </div>
    <div class="title">
      <% if current_user.id == params[:id].to_i %>
        <h6>Add Activity to Specific Day</h6>
        <%= form_for @calendar do |f| %>
          <%= f.date_field :date %>
          <%= f.submit "Select" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>